default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_shop_development
  #username: my_shop
  # The password associated with the postgres role (username).
  #password:
  #host: localhost
  #port: 5432
  
test:
  <<: *default
  database: my_shop_test

production:
  <<: *default
  database: my_shop_production
  username: my_shop
  password: <%= ENV["MY_SHOP_DATABASE_PASSWORD"] %>
